'use strict';
(async()=>{
 const $=id=>document.getElementById(id),root=document.documentElement,host=$('offline-transcript');
 const data=await (await fetch('/snapshot',{cache:'no-store'})).json(),key='offline-position:'+data.vaultId;
 let first=0,restoring=false,timer;const families={system:'system-ui,sans-serif',gothic:'"Bookshop Gothic",sans-serif',myeongjo:'"Bookshop Myeongjo",serif',batang:'"Bookshop Batang",serif',ridi:'"Bookshop RIDI",serif'};
 const node=(tag,cls,text)=>{const e=document.createElement(tag);e.className=cls||'';if(text!==undefined)e.textContent=text;return e;};
 $('offline-title').textContent=data.meta.character+' · '+(data.meta.alias||data.meta.title);$('offline-date').textContent=new Date(data.created).toLocaleString('ko-KR')+' 보관본 · 서버에 연결하지 않아요';
 const prefs=data.preferences||{};let local={};try{local=JSON.parse(localStorage.getItem('offline-style')||'{}');}catch{}
 for(const [id,k,def]of [['off-theme','theme','light'],['off-font','font','system'],['off-line','line','1.85'],['off-padding','padding','24'],['off-size','size','16']]){const v=String(local[k]??prefs[k]??def);$(id).value=[...$(id).options].some(o=>o.value===v)?v:def;$(id).onchange=()=>apply(true);}
 $('off-photos').checked=local.messagePhotos??prefs.messagePhotos??true;$('off-photos').onchange=()=>apply(true);
 $('off-bold').checked=local.bold??prefs.bold??false;$('off-bold').onchange=()=>apply(true);
 function pos(){const top=host.getBoundingClientRect().top;for(const e of host.querySelectorAll('.message')){const r=e.getBoundingClientRect();if(r.bottom>top+1)return {index:Number(e.dataset.index),fraction:Math.max(0,Math.min(1,(top-r.top)/Math.max(1,r.height)))};}return {index:first,fraction:0};}
 function save(){try{localStorage.setItem(key,JSON.stringify(pos()));}catch{}}
 function restore(p){restoring=true;const e=host.querySelector('[data-index="'+p.index+'"]');if(e)host.scrollTop+=e.getBoundingClientRect().top-host.getBoundingClientRect().top+p.fraction*e.getBoundingClientRect().height;requestAnimationFrame(()=>requestAnimationFrame(()=>restoring=false));}
 function apply(remember){const p=pos();root.dataset.messagePhotos=String($('off-photos').checked);root.dataset.theme=$('off-theme').value;root.dataset.readingFont=$('off-font').value;root.dataset.readingBold=String($('off-bold').checked);for(const [k,v]of Object.entries({'--reading-family':families[$('off-font').value],'--reading-size':$('off-size').value+'px','--reading-weight':$('off-bold').checked?'700':'400','--reading-line':$('off-line').value,'--bubble-padding':$('off-padding').value+'px'}))root.style.setProperty(k,v);window.BookshopRich.refresh(host);restore(p);if(remember)try{localStorage.setItem('offline-style',JSON.stringify({theme:$('off-theme').value,font:$('off-font').value,size:$('off-size').value,bold:$('off-bold').checked,line:$('off-line').value,padding:$('off-padding').value,messagePhotos:$('off-photos').checked}));}catch{}}
 function render(p){first=Math.min(Math.max(0,p.index),Math.max(0,data.messages.length-1));window.BookshopRich.clear(host);host.replaceChildren();
  for(const m of data.messages.slice(first,first+30)){const article=node('article','message'+(m.user?' user':'')),bubble=node('div','bubble');article.dataset.index=m.index;const by=node('div','byline');if((m.characterSpeech??(!m.user&&(!m.system||m.name===data.meta.character)))&&typeof data.meta.photo==='string'&&data.meta.photo.length<6000000&&/^data:image\/png;base64,[a-z0-9+/]+=*$/i.test(data.meta.photo)){const box=node('span','avatar message-avatar'),img=node('img');img.src=data.meta.photo;img.alt=m.name+' 프로필';box.append(img);by.append(box);}by.append(node('span','',m.name+' · '+m.date));article.append(by,bubble);host.append(article);
   const mount=(parent,text)=>window.BookshopRich.mount(parent,text,{onResize:change=>{const before=restoring?p:pos();change();restore(before);}});mount(bubble,m.content||'');for(const t of m.translations||[]){const d=node('details','stored-translation'),b=node('div','');d.append(node('summary','',t.label||'저장된 번역'),b);bubble.append(d);mount(b,t.content);}}
  $('off-prev').disabled=first===0;$('off-next').disabled=first+30>=data.messages.length;$('off-page').textContent=(data.messages.length?first+1:0)+' / '+data.messages.length;host.scrollTop=0;restore({...p,index:first});
 }
 for(const b of data.bookmarks||[]){const o=node('option','',(b.index+1)+'번째 · '+(b.note||'책갈피'));o.value=b.index;$('off-marks').append(o);}$('off-marks').onchange=()=>{if($('off-marks').value!=='')render({index:Number($('off-marks').value),fraction:0});};
 const goto=i=>{render({index:i,fraction:0});save();};$('off-first').onclick=()=>goto(0);$('off-last').onclick=()=>goto(Math.max(0,data.messages.length-1));$('off-prev').onclick=()=>goto(Math.max(0,first-30));$('off-next').onclick=()=>goto(first+30);
 function focus(value){const p=pos();root.dataset.focus=String(value);$('off-exit').hidden=!value;restore(p);}$('off-focus').onclick=()=>focus(true);$('off-exit').onclick=()=>focus(false);window.addEventListener('bookshop-content-tap',()=>focus(false));
 host.addEventListener('scroll',()=>{if(restoring)return;clearTimeout(timer);timer=setTimeout(save,300);});document.addEventListener('visibilitychange',save);window.addEventListener('pagehide',save);
 let saved=data.saved||{index:0,fraction:0};try{const p=JSON.parse(localStorage.getItem(key));if(p&&Number.isSafeInteger(p.index)&&p.index>=0&&p.fraction>=0&&p.fraction<=1)saved=p;}catch{}apply(false);render(saved);
})().catch(()=>{document.getElementById('offline-title').textContent='보관본을 열 수 없어요. 목록으로 돌아가 다시 시도해 주세요.';});
