'use strict';
const express=require('express'),{chromium}=require('playwright'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');const c=require('../core.cjs'),plugin=require('../index.cjs');
(async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'silly-nav-')),dirs={root,chats:path.join(root,'chats'),groupChats:path.join(root,'group chats'),characters:path.join(root,'characters')};let browser,server;try{
for(const d of Object.values(dirs))await fs.mkdir(d,{recursive:true});await fs.writeFile(path.join(dirs.characters,'캐릭터.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jDd0AAAAASUVORK5CYII=','base64'));await fs.mkdir(path.join(dirs.chats,'캐릭터'));await fs.writeFile(path.join(dirs.chats,'캐릭터','대화.jsonl'),[{name:'캐릭터',is_system:true,mes:'캐릭터의 첫 발화'},{name:'System',is_system:true,mes:'실제 시스템 안내'},{name:'나',is_user:true,is_system:true,mes:'내 발화'},{name:'캐릭터',is_system:true,extra:{type:'narrator'},mes:'나레이터 안내'},...Array.from({length:30},(_,i)=>({name:'캐릭터',mes:'장면 '+i+' '.repeat(2)+'대화 본문. '.repeat(50)}))].map(JSON.stringify).join('\n'));await c.atomicJson(path.join(await c.stateDir(root),'auth.json'),{salt:'fixture',hash:await c.passwordHash('test-password','fixture')});
const app=express();app.use(express.json());app.use((req,res,next)=>{req.user={directories:dirs};next();});app.get('/csrf-token',(req,res)=>res.json({token:'fixture'}));const router=express.Router();await plugin.init(router);app.use('/api/plugins/silly-bookshop',router);server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});const url='http://127.0.0.1:'+server.address().port+'/api/plugins/silly-bookshop/';browser=await chromium.launch({headless:true,args:['--no-sandbox']});
for(const mode of ['windows','android','iphone-installed','ipad-installed']){
await c.atomicJson(path.join(await c.stateDir(root),'reading.json'),{});const ios=mode.includes('installed'),native=mode==='android',ctx=await browser.newContext({viewport:{width:mode==='iphone-installed'?390:1100,height:850},...(native?{userAgent:'SillyBookshop/0.9.2'}:ios?{userAgent:mode==='iphone-installed'?'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15':'Mozilla/5.0 (Macintosh; Intel Mac OS X) AppleWebKit/605.1.15'}:{})});if(ios)await ctx.addInitScript(()=>{Object.defineProperty(navigator,'standalone',{get:()=>true});Object.defineProperty(navigator,'platform',{get:()=> 'MacIntel'});Object.defineProperty(navigator,'maxTouchPoints',{get:()=>5});});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(url);await page.locator('#password').fill('test-password');await page.locator('#login-form .primary').click();await page.locator('.character').waitFor();assert.equal(await page.locator('#sidebar').isVisible(),true);assert.equal(await page.locator('.chat-head').isVisible(),false);assert.equal(await page.locator('#fold').isVisible(),mode==='windows');await page.locator('.character').click();await page.locator('.thread').click();await page.locator('[data-index="0"] .message-avatar img').waitFor();assert.equal(await page.locator('[data-index="0"] .byline').innerText().then(s=>s.includes('시스템')),false);for(const i of [1,2,3])assert.equal(await page.locator('[data-index="'+i+'"] .message-avatar').count(),0);
const height=await page.locator('.reading-tools button').first().evaluate(e=>e.getBoundingClientRect().height);assert.ok(height<=36&&height>=32);if(mode==='iphone-installed'){await page.addStyleTag({content:':root{font-family:"Bookshop Gothic",sans-serif}'});await page.evaluate(()=>document.fonts.load('400 12px "Bookshop Gothic"','한국어'));}if(mode==='iphone-installed')await page.screenshot({path:'/tmp/bookshop-092-reader.png'});
if(mode==='windows'){await page.locator('#fold').click();assert.equal(await page.locator('#sidebar').isVisible(),false);await page.locator('#fold').click();assert.equal(await page.locator('#sidebar').isVisible(),true);}else assert.equal(await page.locator('#sidebar').isVisible(),false);
await page.evaluate(()=>window.dispatchEvent(new Event('bookshop-open-tools')));
for(const [value,name] of [['pretendard','Pretendard'],['plex','Plex'],['dodum','Dodum'],['hahmlet','Hahmlet']]){
 await page.locator('#font-family').selectOption(value);
 await page.locator('.rich-output').first().evaluate(e=>e._bookshopFontsReady);assert.ok(await page.frameLocator('.rich-output').first().locator('body').evaluate(async(el,name)=>(await el.ownerDocument.fonts.load('700 16px \"Bookshop '+name+'\"','우리 이야기')).length>0,name));
 for(const weight of [400,700])assert.ok(await page.evaluate(async ({weight,name})=>(await document.fonts.load(weight+' 16px "Bookshop '+name+'"','우리 이야기')).length>0,{weight,name}));
}
const gaps=await page.evaluate(()=>{const ids=['theme','reading-size','line-spacing'];const r=ids.map(id=>document.getElementById(id).getBoundingClientRect());return [r[1].top-r[0].bottom,r[2].top-r[1].bottom];});assert.ok(Math.abs(gaps[0]-gaps[1])<1);
await page.locator('#font-family').selectOption('pretendard');
if(mode==='iphone-installed'){await page.addStyleTag({content:':root{font-family:"Bookshop Gothic",sans-serif}'});await page.evaluate(()=>document.fonts.load('400 12px "Bookshop Gothic"','한국어'));}if(mode==='iphone-installed')await page.screenshot({path:'/tmp/bookshop-092-settings.png'});
await page.locator('#message-photos').uncheck();await page.locator('[data-close=tools-dialog]').click();assert.equal(await page.locator('[data-index="0"] .message-avatar').isVisible(),false);await page.reload();await page.locator('[data-index="0"]').waitFor();assert.equal(await page.locator('[data-index="0"] .message-avatar').isVisible(),false);await page.evaluate(()=>window.dispatchEvent(new Event('bookshop-open-tools')));await page.locator('#message-photos').check();await page.locator('[data-close=tools-dialog]').click();await page.locator('[data-index="0"] .message-avatar img').waitFor();assert.equal(await page.locator('[data-index="0"] .message-avatar').isVisible(),true);
await page.locator('#transcript').evaluate(el=>el.scrollTop=650);await page.waitForTimeout(1100);if(ios)await page.locator('#web-home').click();else await page.evaluate(()=>window.dispatchEvent(new Event('bookshop-home')));await page.locator('.character').waitFor();assert.equal(await page.locator('.chat-head').isVisible(),false);assert.equal(await page.locator('#sidebar').isVisible(),true);await page.locator('.character').click();await page.locator('.thread').click();await page.locator('.message').first().waitFor();assert.ok(Number(await page.locator('.message').first().getAttribute('data-index'))>0);assert.deepEqual(errors,[]);await ctx.close();console.log('PASS: '+mode+' home/chat, fold visibility, portraits including flagged character, system/narrator exclusion, toggle persistence, return-to-reading position');}
}finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exitCode=1;});
