'use strict';
const express=require('express'),{chromium}=require('playwright'),fs=require('node:fs/promises'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const c=require('../core.cjs'),plugin=require('../index.cjs');
function png(red=40){
 const crc=b=>{let n=0xffffffff;for(const x of b){n^=x;for(let i=0;i<8;i++)n=(n>>>1)^((n&1)?0xedb88320:0);}return(n^0xffffffff)>>>0;};
 const chunk=(type,data)=>{const name=Buffer.from(type),out=Buffer.alloc(data.length+12);out.writeUInt32BE(data.length);name.copy(out,4);data.copy(out,8);out.writeUInt32BE(crc(Buffer.concat([name,data])),out.length-4);return out;};
 const hdr=Buffer.alloc(13);hdr.writeUInt32BE(16);hdr.writeUInt32BE(16,4);hdr[8]=8;hdr[9]=2;
 const scan=Buffer.alloc(16*(1+16*3));for(let y=0;y<16;y++)for(let x=0;x<16;x++){const i=y*49+1+x*3;scan[i]=red;scan[i+1]=110;scan[i+2]=210;}
 return Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',hdr),chunk('IDAT',require('node:zlib').deflateSync(scan)),chunk('IEND',Buffer.alloc(0))]);
}

(async()=>{
 const root=await fs.mkdtemp(path.join(os.tmpdir(),'silly-personal-')),dirs={root,chats:path.join(root,'chats'),groupChats:path.join(root,'group chats'),characters:path.join(root,'characters')};let browser,server;
 try{
 for(const dir of Object.values(dirs))await fs.mkdir(dir,{recursive:true});
 for(const name of ['가람','나루','다온']){await fs.writeFile(path.join(dirs.characters,name+'.png'),png());await fs.mkdir(path.join(dirs.chats,name));await fs.writeFile(path.join(dirs.chats,name,'긴 원래 대화 이름.jsonl'),Array.from({length:40},(_,i)=>JSON.stringify({name,mes:'<think>SECRET</think>원문 '+i,extra:{display_text:'<think>SECRET</think>아름다운 달빛 '+i,translations:{en:'Moonlight '+i}}})).join('\n'));}
 await c.atomicJson(path.join(await c.stateDir(root),'auth.json'),{salt:'fixture',hash:await c.passwordHash('test-password','fixture')});
 const app=express();app.use(express.json({limit:'1mb'}));app.use((req,res,next)=>{req.user={directories:dirs};next();});app.get('/csrf-token',(req,res)=>res.json({token:'fixture'}));const router=express.Router();await plugin.init(router);app.use('/api/plugins/silly-bookshop',router);server=await new Promise(r=>{const s=app.listen(0,'127.0.0.1',()=>r(s));});const origin='http://127.0.0.1:'+server.address().port;
 browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage(),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(origin))external.push(r.url());});
 const url=origin+'/api/plugins/silly-bookshop/';await page.goto(url);await page.locator('#password').fill('test-password');await page.locator('#login-form .primary').click();await page.locator('.character').first().waitFor();
 await page.locator('#shelf-sort').selectOption('name');assert.equal(await page.locator('.character-name').first().innerText(),'가람');await page.locator('.character').filter({hasText:'다온'}).click();await page.locator('.person-manage').click();await page.locator('#favorite-check').check();await page.getByText('즐겨찾기에 고정했어요.',{exact:true}).waitFor();assert.equal(await page.locator('.character-name').first().innerText(),'★ 다온');
 await page.locator('#cover-file').setInputFiles({name:'cover.png',mimeType:'image/png',buffer:png(220)});await page.locator('#cover-save:not([disabled])').waitFor();await page.locator('#cover-save').click();await page.locator('#person-settings').waitFor({state:'hidden'});
 await page.locator('#tools').click();await page.locator('#library-view').selectOption('covers');await page.locator('#diagnose').click();await page.getByText('실리·책방 연결 정상',{exact:false}).waitFor();assert.ok((await page.locator('#diagnostic-result').innerText()).includes('0.8.1-test.1'));await page.locator('[data-close=tools-dialog]').click();
 const red=async()=>page.locator('.character').first().locator('img').evaluate(async img=>{await img.decode();const cv=document.createElement('canvas');cv.width=cv.height=1;const ctx=cv.getContext('2d');ctx.drawImage(img,0,0,1,1);return ctx.getImageData(0,0,1,1).data[0];});await page.locator('.character').first().locator('img').waitFor();assert.equal(await red(),220);
 await page.reload();await page.locator('.character').first().locator('img').waitFor();assert.equal(await red(),220);assert.equal(await page.locator('.character-name').first().innerText(),'★ 다온');
 // A separate device sees account metadata, while keeping its own list layout.
 const other=await browser.newContext({viewport:{width:1000,height:800}}),pc=await other.newPage();await pc.goto(url);await pc.locator('#password').fill('test-password');await pc.locator('#login-form .primary').click();await pc.locator('.character').first().waitFor();assert.equal(await pc.locator('.character-name').first().innerText(),'★ 다온');assert.equal(await pc.locator('#characters').getAttribute('data-view'),'list');await pc.locator('.character').first().locator('img').waitFor();assert.equal(await pc.locator('.character').first().locator('img').evaluate(async img=>{await img.decode();const cv=document.createElement('canvas');cv.width=cv.height=1;const cx=cv.getContext('2d');cx.drawImage(img,0,0,1,1);return cx.getImageData(0,0,1,1).data[0];}),220);await other.close();
 // Open selected character's chat, save an alias, search visible translations beyond page 1.
 if(await page.locator('.thread').count()===0)await page.locator('.character').first().click();await page.locator('.thread').first().click();await page.locator('.message').first().waitFor();const messageRed=()=>page.locator('.message-avatar img').first().evaluate(async img=>{await img.decode();const cv=document.createElement('canvas');cv.width=cv.height=1;const cx=cv.getContext('2d');cx.drawImage(img,0,0,1,1);return cx.getImageData(0,0,1,1).data[0];});await page.locator('.message-avatar img').first().waitFor();assert.equal(await messageRed(),220);
 await page.locator('#refresh').click();await page.locator('#refresh:not([disabled])').waitFor();await page.locator('.message-avatar img').first().waitFor();assert.equal(await messageRed(),220);
 await page.reload();await page.locator('.message-avatar img').first().waitFor();assert.equal(await messageRed(),220);
 await page.locator('#alias-open').click();await page.locator('#alias-value').fill('달빛 아래');await page.locator('#alias-form .primary').click();await page.locator('#alias-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('#title').innerText(),'달빛 아래');
 await page.locator('#chat-search-open').click();await page.locator('#chat-search-query').fill('SECRET');await page.locator('#chat-search-submit').click();await page.getByText('0개 찾음',{exact:false}).waitFor();assert.equal(await page.locator('.search-result').count(),0);
 await page.locator('#chat-search-query').fill('Moonlight 35');await page.locator('#chat-search-submit').click();await page.locator('.search-result').waitFor();await page.locator('.search-result').click();await page.locator('[data-index="35"].search-hit').waitFor();
 await page.evaluate(()=>{const v=window.BookshopOfflineStatus.current();window.BookshopOfflineStatus.update({...v,exists:false});});assert.equal(await page.locator('#offline-state').isVisible(),false);assert.equal(await page.locator('#offline-state').innerText(),'');
 // Native status callback contract: same account/chat only; changed revision shows update hint.
 await page.evaluate(()=>{const v=window.BookshopOfflineStatus.current();window.BookshopOfflineStatus.update({...v,created:Date.now(),exists:true});});assert.ok((await page.locator('#offline-state').innerText()).includes('오프라인 보관됨'));assert.ok(!(await page.locator('#offline-state').innerText()).includes('업데이트 필요'));
 await page.evaluate(()=>{const v=window.BookshopOfflineStatus.current();window.BookshopOfflineStatus.update({...v,revision:'old',created:Date.now(),exists:true});});assert.ok((await page.locator('#offline-state').innerText()).includes('업데이트 필요'));
 await page.locator('#home').click();await page.locator('#search').fill('달빛 아래');assert.equal(await page.locator('.character').count(),1);await page.locator('.character').click();assert.ok((await page.locator('.thread').innerText()).includes('달빛 아래'));await page.locator('.person-manage').click();await page.locator('#cover-remove').click();await page.locator('#person-settings').waitFor({state:'hidden'});await page.locator('.character').first().locator('img').waitFor();assert.equal(await red(),40);
 await page.locator('#lock').click();await page.getByText('책방을 잠갔어요.',{exact:true}).waitFor();assert.equal(await page.locator('.search-result,#cover-preview img').count(),0);assert.equal(await page.evaluate(()=>window.BookshopOfflineStatus.current()),null);assert.ok(!(await page.evaluate(()=>JSON.stringify(localStorage))).includes('달빛 아래'));
 await page.route('**/api/plugins/silly-bookshop/status',route=>route.fulfill({status:404,contentType:'text/html',body:'Not found'}));await page.locator('#gate-diagnose').click();await page.getByText('책방 플러그인 주소를 찾지 못했어요.',{exact:false}).waitFor();assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 await context.close();const old=await browser.newContext({userAgent:'SillyBookshop/0.7.1'}),op=await old.newPage();await op.goto(url);assert.ok((await op.locator('#compatibility-note').textContent()).includes('APK 0.8.1'));await old.close();
 console.log('PASS: unsaved banner hidden; chosen photo in list and message avatars survives refresh/reload; favorites/sorting, real cover selection and removal, cross-device metadata, original list preserved, aliases and search, hidden reasoning absent, translation jump, native status contract, lock cleanup, old-APK warning, missing-plugin diagnosis, no external requests.');
 }finally{if(browser)await browser.close();if(server)await new Promise(r=>server.close(r));await fs.rm(root,{recursive:true,force:true});}
})().catch(e=>{console.error(e);process.exitCode=1;});
