'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs/promises'),os=require('node:os'),path=require('node:path');
const c=require('../core.cjs'),reading=require('../reading.cjs');
async function fixture(t){const root=await fs.mkdtemp(path.join(os.tmpdir(),'bookshop-reading-'));t.after(()=>fs.rm(root,{recursive:true,force:true}));const d={root,chats:path.join(root,'chats'),groupChats:path.join(root,'group chats'),characters:path.join(root,'characters')};for(const dir of Object.values(d))await fs.mkdir(dir,{recursive:true});await fs.mkdir(path.join(d.chats,'A'));await fs.writeFile(path.join(d.characters,'A.png'),Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl6P6sAAAAASUVORK5CYII=','base64'));await fs.writeFile(path.join(d.chats,'A','one.jsonl'),Array.from({length:35},(_,i)=>JSON.stringify({name:'A',mes:'<think>SECRET</think>hello '+i,extra:{display_text:'<think>SECRET</think>번역 '+i,translations:{en:'other '+i},apiKey:'API_SECRET'}})).join('\n'));return d;}
const id=c.encode(['chat','A','one.jsonl']);
test('bookmarks and visits isolated, bounded, serialized, source unchanged, removed cards excluded',async t=>{const a=await fixture(t),b=await fixture(t),file=path.join(a.chats,'A','one.jsonl'),before=await fs.readFile(file);
 await Promise.all([0,1,2].map(index=>reading.bookmarks(a,id,{index,note:'메모 '+index,remove:false})));assert.equal((await reading.bookmarks(a,id)).length,3);assert.deepEqual(await reading.bookmarks(b,id),[]);
 await reading.bookmarks(a,id,{index:1,note:'수정',remove:false});assert.equal((await reading.bookmarks(a,id)).find(x=>x.index===1).note,'수정');await reading.bookmarks(a,id,{index:1,note:'',remove:true});assert.equal((await reading.bookmarks(a,id)).length,2);
 for(const change of [{index:-1,note:'',remove:false},{index:35,note:'',remove:false},{index:1,note:'x'.repeat(301),remove:false}])await assert.rejects(()=>reading.bookmarks(a,id,change),{status:400});
 await reading.visit(a,id);let chats=await c.catalog(a);assert.equal((await reading.recent(a,chats))[0].position.index,0);assert.deepEqual(await reading.recent(b,chats),[]);await c.position(a.root,id,{index:20,fraction:0.4});assert.equal((await reading.recent(a,chats))[0].position.index,20);
 assert.deepEqual(await fs.readFile(file),before);await fs.unlink(path.join(a.characters,'A.png'));assert.deepEqual(await reading.recent(a,await c.catalog(a)),[]);await assert.rejects(()=>reading.snapshot(a,id),{status:404});
});
test('offline snapshot includes all pages and filtered translations, excludes secrets and fails closed on regex errors',async t=>{const a=await fixture(t);await reading.bookmarks(a,id,{index:3,note:'장면',remove:false});let s=await reading.snapshot(a,id);assert.equal(s.messages.length,35);assert.equal(s.bookmarks[0].note,'장면');assert.ok(!JSON.stringify(s).includes('SECRET'));assert.equal(s.messages[34].content,'번역 34');assert.equal(s.messages[0].translations[0].content,'other 0');await assert.rejects(()=>reading.snapshot(a,id,()=>true),{status:408});
 await fs.writeFile(path.join(a.root,'settings.json'),JSON.stringify({extension_settings:{regex:[{findRegex:'/[invalid/',replaceString:'',placement:[1,2],markdownOnly:true}]}}));await assert.rejects(()=>reading.snapshot(a,id),{status:409});
});
